# Generated by Django 5.0.6 on 2024-06-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_register_email_alter_register_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
