# Generated by Django 5.0.6 on 2024-06-14 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_image_alter_register_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='image',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
